# Version 0.0.1
FROM tbmgmt_tbmgmt

MAINTAINER Matthias Vill "m_vill04@wwu.de"

# Most of this file is copied from https://github.com/docker-library/tomcat/blob/e36c4044b7ece1361f124aaf3560c2efd888b62f/8-jre8/Dockerfile

ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

# see https://www.apache.org/dist/tomcat/tomcat-8/KEYS
# We explicitly state the key-IDs to not allow interference by a hacked website. If you don't mind, you can use one
# of the following two approaches.

#RUN wget -O - https://www.apache.org/dist/tomcat/tomcat-8/KEYS | gpg --import
#RUN gpg --keyserver pool.sks-keyservers.net --recv-keys \
#    $(wget -O - https://www.apache.org/dist/tomcat/tomcat-8/KEYS \
#        | gpg --with-colon \
#        | grep -e "^pub" \
#        | cut -d : -f 5)
RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys \
	05AB33110949707C93A279E3D3EFE6B686867BA6 \
	07E48665A34DCAFAE522E5E6266191C37C037D42 \
	47309207D818FFD8DCD3F83F1931D684307A10A5 \
	541FBE7D8F78B25E055DDEE13C370389288584E7 \
	61B832AC2F1C5A90F0F9B00A1C506407564C17A3 \
	79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED \
	9BA44C2621385CB966EBA586F72C284D731FABEE \
	A27677289986DB50844682F8ACB77FC2E86E29AC \
	A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 \
	DCFD35E0BF8CA7344752DE8B6FB21E8933C60243 \
	F3A04C595DB5B6A5F1ECA43E3B7BBB100D811BBE \
	F7DA48BB64BCB84ECBA7EE6935CD23C10D498E23 \
	713DA88BE50911535FE716F5208B0AB1D63011C7

ENV TOMCAT_MAJOR 8
#ENV TOMCAT_VERSION 8.0.52
ENV TOMCAT_VERSION 8.5.32
ENV TOMCAT_TGZ_URL https://www.apache.org/dist/tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz

RUN set -x \
	&& wget "$TOMCAT_TGZ_URL" -O tomcat.tar.gz \
	&& wget "$TOMCAT_TGZ_URL.asc" -O tomcat.tar.gz.asc \
	&& gpg --verify tomcat.tar.gz.asc \
	&& tar -xvf tomcat.tar.gz --strip-components=1 \
	&& rm bin/*.bat \
	&& rm tomcat.tar.gz* \
	&& rm -rf "$CATALINA_HOME/webapps/" \
	&& mkdir -p "$CATALINA_HOME/webapps/" \
	&& cp "/install/web-${TBMGMT_VERSION}.war" "$CATALINA_HOME/webapps/ROOT.war" \
    && rm -rf /install \
    && mkdir -p /tbmgmt/files  \
    && chown -R testbed-user "$CATALINA_HOME" /tbmgmt/files

EXPOSE 8080
#ENTRYPOINT ["gosu", "testbed-user", "catalina.sh", "run"]
ENTRYPOINT ["catalina.sh", "run"]
